[package]
name = "rust-ethereum-abi-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum_abi = "0.4.0"
web3 = "0.18.0"
